### ISSUE TITLE
Schematic or connection between RPBee nRF52 pinout and MDBT42Q module pinout

### ISSUE THREAD

**Issue by nduongn** [JKSOFTEdu/rpbee_nrf52#1]
Hi, Can you provide me the schematic or the connection between RPBee nRF52 pinout and MDBT42Q module pinout?

**Comment by jakorten** [comment]
Hi Mark, of course! I'll upload it right away.

Direct link: http://jksoftedu.nl/wp-content/uploads/2017/06/Schematic_nRF52_Bee.png
Context: http://jksoftedu.nl/hardware/nrf52/

Note: at this point the fixed Adafruit nRF52 source is better than this version.

**Comment by nduongn** [comment]
Hi Jakorten,
Thanks but I don't see the connection between DI0:DI5 in XBEE with MDBT42Q  module. Can you show me that?
BRs.

**Comment by jakorten** [comment]
I see what you mean. Probably this is from an onder iteration. I will have a better look at it and upload the most current version asap.

Update: This is a better version: http://jksoftedu.nl/wp-content/uploads/2017/06/Schematic_nRF52_Bee-1.png

**Comment by nduongn** [comment]
Many thanks for your help.
